### ISSUE TITLE
Model selection field does not show up when trying to use perplexity openai endpoint

### ISSUE THREAD

**Issue by d4g** [nextcloud/integration_openai#105]
### Which version of integration_openai are you using?

2.0.1

### Which version of Nextcloud are you using?

v29.0.2

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

126.0.1 (64-bit)

### Describe the Bug

I try to configure the openai endpoint of perplexity, bit the model selection just does not show up.
![nextcloud_perplexity](https://github.com/nextcloud/integration_openai/assets/723199/397fd3c6-9917-4f12-aab3-8312019c6824)

### Expected Behavior

I can select the model.

### To Reproduce

Try to use perplexity as ai endpoint.

**Comment by d4g** [comment]
Following to that, all requests fail with "assistant errror" but I don't see any errors in the log.

**Comment by kyteinsky** [comment]
Hi, we assumed every OpenAI-compatible endpoint would have `/v1/` in their URL. In your example it seems it can work without it so the fix would be to get rid of the mandatory `v1` in the url and require it specifically in the "Service URL".
In addition to this, there needs to be a migration of the existing service url config value. See the migration in https://github.com/nextcloud/integration_github/pull/114 for an example.

^ hint for anyone who wants to work on the fix.

**Comment by d4g** [comment]
I created a workaround using litellm as a proxy for perplexity.

**Comment by julien-nc** [comment]
I think there are 2 ways to solve this:

1. By adding a setting next to the "Service URL" one to choose the root path of the API. This "path" setting would be "/v1/" by default. This would not break any thing so no migration would be needed.
2. By not appending the "/v1" anymore to the service URL and asking the admins to set the full API URL. For example `https://my.localai.org/v1`. So the existing stored "Service URL" would need to be migrated when upgrading this app, a "/v1" would be appended.

**Comment by edward-ly** [comment]
> In addition to this, there needs to be a migration of the existing service url config value. See the migration in [nextcloud/integration_github#114](https://github.com/nextcloud/integration_github/pull/114) for an example.

Sorry if I'm not understanding something, but I don't see a reason for encrypting such URLs if they're not as sensitive as API keys or passwords.

> I think there are 2 ways to solve this:
> 
>     1. By adding a setting next to the "Service URL" one to choose the root path of the API. This "path" setting would be "/v1/" by default. This would not break any thing so no migration would be needed.
> 
>     2. By not appending the "/v1" anymore to the service URL and asking the admins to set the full API URL. For example `https://my.localai.org/v1`. So the existing stored "Service URL" would need to be migrated when upgrading this app, a "/v1" would be appended.
> 
> 
> Both solutions would give the freedom to admins to use services that implement an OpenAI-compatible API but are not served under a "/v1" path.
> 
> Additionally there could be a "preview" in the settings to show an example full endpoint URL. Something like: "With the current configuration, the target URL used to get the models is `https://my.localai.org/custom/path/models`" So it would be easier to admins to understand how they can fix the service URL if they set a bad value.

(2) makes more sense to me. I don't think we should assume anything regarding the API version on our side. The preview could say something like: "This should include the full root path of your LocalAI API.", and the default URL would be https://api.openai.com/v1.

**Comment by kyteinsky** [comment]
> Sorry if I'm not understanding something, but I don't see a reason for encrypting such URLs if they're not as sensitive as API keys or passwords.

Yeah sorry I should've added more context. Julien did a pretty good job there.
I meant that, for the setups that have a custom Service URL set, they would be following the current rule of not having a `/v1` at the end. If we make this change on its own, those setups would break since now the URLs would be something like `http://localhost:8080/images/generations` instead of `http://localhost:8080/v1/images/generations` for local AI.
To not break the existing configured setups, we need to add a `/v1` to all of them. This change to the value should be done through a migration, a change similar to the linked PR: https://github.com/nextcloud/integration_openai/blob/main/lib/Migration/Version030102Date20241003155512.php
But it can be done through IAppConfig too instead of the DB migration.

**Comment by edward-ly** [comment]
A migration seems unavoidable to me, unless you mean that IAppConfig can be used as part of the migration. I can try it out and see how it goes, or I can stick with what worked in previous PRs too.

**Comment by julien-nc** [comment]
There's a confusion in the terms we use here. Yes we should use a migration step to change the existing stored values. In this migration step we can either touch the DB directly or use IAppConfig. I agree it's better to use IAppConfig for app-specific values (oc_appconfig stuff). 

But in other apps where we have to migrate oc_preference values (user-specific values), it is very convenient to touch the DB directly because it is sketchy and expensive to go with IConfig and iterate on all users. I think, for user values, DB queries make sense.

About encryption, that was not the point of mentioning https://github.com/nextcloud/integration_github/pull/114 . The goal was just to show an example of migration step that changes oc_appconfig values.

Anyway, all good in the PR 👍
