### ISSUE TITLE
Cannot check quota for anonymous user error

### ISSUE THREAD

**Issue by l3ochan** [nextcloud/integration_openai#145]
### Which version of integration_openai are you using?

30.0.1.2

### Which version of Nextcloud are you using?

30.0.1

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Brave Version 1.70.126 Chromium: 129.0.6668.100

### Describe the Bug

I can't talk to any third party LLM. It loads indefinitely the answer and in the logs, I get an error saying the server cannot check the quota for anonymous user

### Expected Behavior

The server should check the quota for the current user and send the request to the LLM provider, then display the answer when it's available

### To Reproduce

1) Install nextcloud assistant and the OpenAI/LocalAI integration
2) I use openai's chatgpt, so I registered an API key and added balance to my openAI api account
3) Select a valid OpenAI model (in my case, "GPT 4o mini (system)") 
4) Open the nextcloud assistant's UI and go to the  Chat With AI section
5) send a request, it loads indefinitely
6) wait a few minutes
7) check the logs, You'll see something like the log entry below

```json
{
  "reqId": "aDMWp5x1MSSJqRhCVq1N",
  "level": 2,
  "time": "2024-10-17T19:40:03+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "integration_openai",
  "method": "",
  "url": "--",
  "message": "Cannot check quota for anonymous user",
  "userAgent": "--",
  "version": "30.0.1.2",
  "data": {
    "app": "integration_openai"
  },
  "id": "6711683c988e8"
}
```

**Comment by simonquasar** [comment]
can confirm same issue since I upgraded from 29 to 30 with all tasks with "OpenAI" as task processor set. 
(DALLE-2 ImageGeneration works for me, Transcribe audio not tested.)

After the request is sent, the Assistant UI is stuck waiting to render the incoming message.

I think it's an urgent bug to address since when checking the OpenAI Dashboard, the API calls are made and processed by OpenAI, causing credit utilisation (both Input AND Output Tokens).

```
{
  "reqId": "Y8ZCXARSkaXuwIPkRQfv",
  "level": 2,
  "time": "2024-10-19T10:55:01+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "integration_openai",
  "method": "",
  "url": "--",
  "message": "Cannot check quota for anonymous user",
  "userAgent": "--",
  "version": "30.0.0.14",
  "data": {
    "app": "integration_openai"
  },
  "id": "67139cd59d40c"
}
```

**Comment by l3ochan** [comment]
> can confirm same issue since

Oof, this is reassuring. Since I did the upgrade to NC30, my instance has been so unstable. I'm getting hundreds of errors in the logs that I wasn't getting before. Hope they get this sorted out quickly.

**Comment by JoaoVictorLouro** [comment]
Also affecting my NC30 instance, updating resulted in the same issues.
```
[integration_openai] Warning: Cannot check quota for anonymous user
	from ? by -- at Oct 22, 2024, 12:20:01 AM

{"reqId":"m6l9hXWgwKlb1iYYIc74","level":2,"time":"2024-10-22T03:20:01+00:00","remoteAddr":"","user":"--","app":"integration_openai","method":"","url":"--","message":"Cannot check quota for anonymous user","userAgent":"--","version":"30.0.1.2","data":{"app":"integration_openai"},"id":"67171a18af1b0"}
```

I find it very weird that its sending it as an `anonymous` user. I mean, is it because I dont have a per user AI setup? or is it something else?

**Comment by l3ochan** [comment]
Weird thing is that it works sometimes for one prompt, then stops working alltogether, then it outputs the same log entry.

**Comment by mitexleo** [comment]
For me the assistant UI works fine. But this error shows up when I mention the assistant from a Talk room.

**Comment by julien-nc** [comment]
#153 should get rid of the `Cannot check quota for anonymous user` warning logs.
This was a bug but it shouldn't have blocked any task.

When submitting a task, are you sure it "loads indefinitely"?
Since NC 30, tasks are running in background jobs. So there is a delay before they get executed (until the next cron.php execution). To get rid of this delay, you can setup one or more workers. There is an occ command that "watches" specific background jobs in the queue and runs them immediately.
https://docs.nextcloud.com/server/latest/admin_manual/ai/overview.html#improve-ai-task-pickup-speed

Does that help?

**Comment by l3ochan** [comment]
I tried sending a request, then executing the cron.php and you are right. Requests are sent when the background job is ran. 

========================
For anyone that has the same issue, I followed those directions --> https://docs.nextcloud.com/server/latest/admin_manual/ai/overview.html#improve-ai-task-pickup-speed

I now have 4 workers on my server that wait for user requests and they are processes instantaneously.

**Comment by mitexleo** [comment]
This issue is yet to be fixed. To reproduce:

1. Enable Nextcloud Assistant Bot in Talk room
2. Mention @assistant and ask any question 

Raw Entry:

{"reqId":"vGcEueE9zd8XA9VdvJcJ","level":2,"time":"2024-11-21T12:41:47+00:00","remoteAddr":"","user":"--","app":"integration_openai","method":"","url":"--","message":"Cannot check quota for anonymous user","userAgent":"--","version":"30.0.2.2","data":{"app":"integration_openai"},"id":"673f2baa7f201"}
