### ISSUE TITLE
custam url

### ISSUE THREAD

**Issue by badsmoke** [nextcloud/integration_openai#15]
can i specify a custom url?

i would like to try this with [localai](https://github.com/go-skynet/LocalAI), an openai comtable api endpoint

**Comment by julien-nc** [comment]
Hey, thanks for the suggestion. Could you try replacing `https://api.openai.com/v1/` with your localai instance URL in `lib/Service/OpenAiAPIService.php`?
If it works well I'll add an admin setting to make this URL configurable and disable whatever cannot be done with localai.

Image generation is not possible in localai, right?

**Comment by rutgerputter** [comment]
> Hey, thanks for the suggestion. Could you try replacing `https://api.openai.com/v1/` with your localai instance URL in `lib/Service/OpenAiAPIService.php`? If it works well I'll add an admin setting to make this URL configurable and disable whatever cannot be done with localai.
> 
> Image generation is not possible in localai, right?

This works great actually :smile: 
![image](https://github.com/nextcloud/integration_openai/assets/46106259/1ff5dfe4-6584-4146-a531-31b4b959760a)

The code on line 292 is now: `$url = 'http://<localai ip>:<port>/v1/' . $endPoint;`

**Comment by julien-nc** [comment]
@rutgerputter Thanks for testing this. I would also need to know which feature works and which does not. It would be nicer to disable/hide what's not possible to do with LocalAI.

**Comment by rutgerputter** [comment]
> @rutgerputter Thanks for testing this. I would also need to know which feature works and which does not. It would be nicer to disable/hide what's not possible to do with LocalAI.

Indeed! LocalAI technically supports all models that replace their OpenAI equivalents. But it is up to the admin which models they want to enable. For instance: I will only be running a Text Generation Model (vicuna), because of RAM constraints.

I tried Image generation but ran out of RAM very quickly.
Whisper support is also there for LocalAI, but again, up to the admin to enable it or not.

Please see here what LocalAI can do:
https://github.com/go-skynet/LocalAI/#model-compatibility-table

But what I'm trying to say is that it would be pretty hard to check which features are enabled from this service. GOing with a simple "checkbox" approach in the connected accounts settings would also make it pretty easy to dis/enable certain features.

**Comment by MB-Finski** [comment]
As far as I can tell, this feature is working as expected. Closing this issue for now. Feel free to comment or open a separate issue if some LocalAI features are not working for you.

-Sami
