### ISSUE TITLE
Migration to 2.0.0 Failed

### ISSUE THREAD

**Issue by SNThrailkill** [nextcloud/integration_openai#95]
### Which version of integration_openai are you using?

2.0.0

### Which version of Nextcloud are you using?

28.0.4

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 124

### Describe the Bug

When attempting to update the application, whether by using OCC in CLI or through UI, both result in the following message:

```
Exception: Database error when running migration 020000Date20240325142435 for app integration_openai
Index "openai_prompt_userid" does not exist on table "oc_openai_prompts".
Update failed
```

This failure is due to the DB migration failing, specifically [here](https://github.com/nextcloud/integration_openai/blob/d75c9568631d0bc193a99fbcc2380e76b2645af4/lib/Migration/Version020000Date20240325142435.php#L32), where it tries to drop the indexes and then the tables. In looking at my own Postgres DB I saw that my indexes were named `idx_2XXXXX_openai_prompt_userid`. For some reason it failed to drop them. I dropped the table manually and then the upgrade failed again trying to drop the `openai_i_gen_hash` index. So I dropped the table manually and then it happened again on the final step. Dropping the final table resulted in the migration successfully completing.

### Expected Behavior

Migration to complete successfully.

### To Reproduce

Unfortunately I did not get any screenshots of the issue occurring. I also dont have much more detail besides I upgraded from version 1.21 to the new 2.0.0 version using the UI where I encountered this issue. I'm happy to provide more details as requested.

**Comment by julien-nc** [comment]
Thanks for reporting this. I'm not sure why the indexes are not found while the tables exist... They were created together:
https://github.com/nextcloud/integration_openai/commit/5fb76fdecf325e2d2307d5d21a8eedc7a2e94cb0#diff-d64f991736833913f3659ff5285e2076b5d7805197c8bb93d98941ac5f09d629L53

Maybe the DB abstraction tools behave differently for Postgres and created those indexes with different names...
Anyway, safer to check before deleting indexes. Should be fixed with 1ff6a3f09315c6221b6e63743db0161bb4f6ca46 . Will do more checks in the future.
